name: Build and publish

on:
  push:
    branches:
      - main
    paths:
      - "**/*.tex"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Release, Build and publish
        uses: SamoKopecky/.github/.github/actions/latex-to-release-pdf@main
        with:
          release_url: ${{ steps.create_release.outputs.release_url }}
          file_name: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.event.client_payload.repository }}

